### ISSUE TITLE
New Tab URL parameters from data columns

### ISSUE THREAD

**Issue by marcwiest** [Kholid060/automa#11]
**Is your feature request related to a problem? Please describe.**
I'd like to incorporate text strings from the data column into the new-tab action.

**Describe the solution you'd like**
For example, `https://google.com/search?q=[browser-automation-app]`, where `[browser-automation-app]` would be an entry from the data columns.

**Describe alternatives you've considered**
It seems the only option currently is to get an export along with the new-tab option, and then fabricate the URL myself.

**Additional context**
Nothing

**Comment by Kholid060** [comment]
That's a good idea, but a data column key may have multiple values because it's stored as an array object. For example 
```js
[
  { 'data-column-app': 'data 1' },
  { 'data-column-app': 'data 2' },
  { 'data-column-app': 'data 3' }
  ...
]
```
How to tell which data is the workflow should take? Should it use the index of the data e.g. `[data-column-app@0]` to take the first data of the data columns? Or add a looping block to iterate the data columns? So you can take the current iterate data by `[iteration@data-column-app]`.

**Comment by marcwiest** [comment]
Would `[0.data-key]` or even deeper `[0.data-key.deeper-key]` work? If first character is not a number, 0 (zero) could be implied. For example `[data-key.deeper-key]` would be equal to `[0.data-key.deeper-key]`. Dot notation is intuitive.

**Comment by marcwiest** [comment]
This would even work for data that is structured the following way `[{0: 'value'}]`. If you were to call the data via the URL like so`http://example.com/[0]` you would ask for the first entry of the array, but because you are only asking for a single value, you could asume that the user actually was looking for the first key in the object. Wereas `http://example.com/[0.0]` would retrieve the same value.

**Comment by Kholid060** [comment]
I've added this feature in v0.3.0 (#15). You can use this feature by writing `[keyword@path]`. There are two keywords that you can use which are `data` and `prevBlockData`.  Use the `data` keyword to get data from the data columns, and use `prevBlockData` if you want to get data from the previous block. You can write the data key in the `path` part, and a nested key will work too, but when you're using a nested key, I don't think you'll get the result you expected because the data columns only support text, number, and boolean data type for now. And for syntactic sugar, you can write all the syntax that you mentioned. Like  `[data@data-key.deeper-key]` would equal to `[data@0.data-key.deeper-key]` and `[data@0]` would equal to `[data@0.0]`. TBH, I don't know what I should call this feature, and if you have a better name for this feature feel free to share
