### ISSUE TITLE
sync

### ISSUE THREAD

**Issue by bobyang3** [Kholid060/automa#114]
**Is your feature request related to a problem? Please describe.**
I have multiple computers, it is hard to export and import to multiple computers. In addition, I need to redo the same steps for any updates.

**Describe the solution you'd like**
Sync to somewhere like Github personal config like VSCode sync.

**Describe alternatives you've considered**
sync to a secure location in the cloud and can be sync down to each machine.

thanks

**Comment by Kholid060** [comment]
I don't have enough resources to add a sync feature to the extension so in meantime, you have to do it manually

**Comment by flossgeek** [comment]
Perhaps this could be easily solved by allowing Automa to read from a json file (which contains all the data) located in the extension folder? On my system the extension data is located in ~/.config/chromium/Default/Extensions/"random string"/1.7.2_0. Dropping a (backed up) json file in there would be a very convenient solution for automation, instead of clicking through the Automa GUI for every machine.

**Comment by Kholid060** [comment]
> Perhaps this could be easily solved by allowing Automa to read from a JSON file (which contains all the data) located in the extension folder? On my system the extension data is located in ~/.config/chromium/Default/Extensions/"random string"/1.7.2_0. Dropping a (backed up) json file in there would be a very convenient solution for automation, instead of clicking through the Automa GUI for every machine.

Automa already had sync workflows feature but I disable it. And dropping a JSON file into the extension folder can be an alternative solution, I'll consider adding it.

**Comment by anshul-031** [comment]
Any updates on it?
