### ISSUE TITLE
screenshot's name not support {{ xxxx }} ?

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#231]
![image](https://user-images.githubusercontent.com/20383505/147633579-08baf9fa-cfe8-4ce1-a86f-83f26f664b52.png)

screenshot's name not support {{}}

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/147638267-67c8f674-bc71-4512-a2d2-b9c2a0ce4ef3.png)

We must use dataColumns@0.column   ,it works

**Comment by Kholid060** [comment]
Have you added `name` as a column like an image below? Because if not, Automa will convert all the object keys that you returning in **Javascript code** block as `column`.

![image](https://user-images.githubusercontent.com/22908993/147639436-8013d51a-53bd-47f3-a6ff-7890fe691383.png)

And you can use `prevBlockData` instead of `dataColumns`, for example `{{prevBlockData@name}}`

**Comment by whwh656** [comment]
{{prevBlockData@name}} it works! thans you
