### ISSUE TITLE
Keyboard shortcut does not work.

### ISSUE THREAD

**Issue by hengtangum** [Kholid060/automa#24]
**Describe the bug**
Keyboard shortcuts do not work as expected. I recorded shortcuts like Ctrl-m, Ctrl-Alt-t, etc. None of them can fire, even on the page of automa. 

Context: Windows, Chrome v95. (automa extension)

**Comment by Kholid060** [comment]
Keyboard shortcuts only work when you're on a website and it focused, and when you're on a page that has a `chrome://` prefix or on a chrome extension page it won't work. This is because chrome doesn't have an API to add custom keyboard shortcuts directly into the browser, so instead, I injected the keyboard shortcuts into the website. And after you add the keyboard shortcut, make sure you reload the page to make it work.

**Comment by hengtangum** [comment]
I see, thanks.
