### ISSUE TITLE
{{ }}

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#243]
automa v12.0
![image](https://user-images.githubusercontent.com/20383505/147897816-846ca6de-8efe-4ce9-92d3-4cba8f416124.png)
![image](https://user-images.githubusercontent.com/20383505/147897836-6902f801-c563-4309-abf3-41d777a3e3ef.png)
![image](https://user-images.githubusercontent.com/20383505/147897845-c7fbf61d-0f6a-44dd-9efe-c3b35c77d8fb.png)
![image](https://user-images.githubusercontent.com/20383505/147897881-e3c6ce4d-cbe2-415d-96c0-834bee2662c5.png)
![image](https://user-images.githubusercontent.com/20383505/147898359-5c5fb550-13e0-4dc2-86d6-bb928ca93b68.png)

I try add double quote in {{prevBlockData@ret }} it doesn't work either

**Comment by Kholid060** [comment]
Have you checked whether the `ret` data exist in the workflow log?

![chrome_WEHRj5Gi6W](https://user-images.githubusercontent.com/22908993/147910448-21bb256c-036c-447d-81c7-712c13e0ad08.png)

And I think there's an error in your javascript code, you can't re-assign a variable that you declared with `const` and use `let` instead.

```js
let ret = 0

if (textlen == 3) {
  ret = 1;
} else {
  ret = 'ddd'
}

automaNextBlock({ ret });
```

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/147928969-8fca5198-16bb-476f-9717-ff2d94111af3.png)
![image](https://user-images.githubusercontent.com/20383505/147929098-5617ae31-ef86-41f5-a8ec-6f2678d206d2.png)

The root cause is the  automaRefData() don't get value, if I want to get the arrary of get text

**Comment by Kholid060** [comment]
Have you tried write `automaRefData('dataColumns', '0.test')`, it's cause an error because Automa doesn't recognise `text` column.

![147929098-5617ae31-ef86-41f5-a8ec-6f2678d206d2](https://user-images.githubusercontent.com/22908993/148015154-38bc2b90-869b-43fb-9613-f27ca6375569.png)
![147928969-8fca5198-16bb-476f-9717-ff2d94111af3](https://user-images.githubusercontent.com/22908993/148015174-bfd03a97-e0a3-41c9-8a51-852dfbc89b70.png)

**Comment by whwh656** [comment]
> Have you tried write `automaRefData('dataColumns', '0.test')`, it's cause an error because Automa doesn't recognise `text` column.
> 
> ![147929098-5617ae31-ef86-41f5-a8ec-6f2678d206d2](https://user-images.githubusercontent.com/22908993/148015154-38bc2b90-869b-43fb-9613-f27ca6375569.png) ![147928969-8fca5198-16bb-476f-9717-ff2d94111af3](https://user-images.githubusercontent.com/22908993/148015174-bfd03a97-e0a3-41c9-8a51-852dfbc89b70.png)

I try it it doesn't work 
[testbaidu.txt](https://github.com/Kholid060/automa/files/7806120/testbaidu.txt)

**Comment by Kholid060** [comment]
> I try it it doesn't work [testbaidu.txt](https://github.com/Kholid060/automa/files/7806120/testbaidu.txt)

Can you explain what the workflow suppose to do? Because it's working when I tested it

![image](https://user-images.githubusercontent.com/22908993/148314215-fbb574f3-066e-4234-bb29-cf7d129e0482.png)
![image](https://user-images.githubusercontent.com/22908993/148314611-3dcc3127-e1e2-41e5-8714-55c082accfc8.png)

**Comment by whwh656** [comment]
![image](https://user-images.githubusercontent.com/20383505/148319660-3bb88dff-c78a-457b-8e36-c6d285c6fbbe.png)
![image](https://user-images.githubusercontent.com/20383505/148319708-8c4d3234-458b-43f0-a8c9-92204f78f4b8.png)


> > I try it it doesn't work [testbaidu.txt](https://github.com/Kholid060/automa/files/7806120/testbaidu.txt)
> 
> Can you explain what the workflow suppose to do? Because it's working when I tested it
> 
> ![image](https://user-images.githubusercontent.com/22908993/148314215-fbb574f3-066e-4234-bb29-cf7d129e0482.png) ![image](https://user-images.githubusercontent.com/22908993/148314611-3dcc3127-e1e2-41e5-8714-55c082accfc8.png)

the workflow is green ,but  srceenshot'name   doesn't get from javascrit block

**Comment by Kholid060** [comment]
It doesn't work because the `prevBlockData` object doesn't have the `ret` key. Because in the javascript block you write `automaRefData({ a })`.
To fix this you can write `automaRefData({ ret })`, or if you want to name the screenshot based on the column length you can write `automaRefData({ ret: a })`.

```js
const a = automaRefData('dataColumns', '0.test').length;
var ret = 0
automaNextBlock({ ret: a })
```

**Comment by whwh656** [comment]
thanks
