### ISSUE TITLE
block link

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#259]
Can you help me explain the block of  link ? I am confused about it

**Comment by Kholid060** [comment]
It's for opening an URL that an [anchor](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) element have.

![image](https://user-images.githubusercontent.com/22908993/148678033-ce3390bb-4fee-416c-8408-7478d761ffd8.png)

Because sometimes an anchor element has [`target="_blank"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target) attribute which when it clicked using the **Click element** block, for example, it will open a new tab. And because it opened a new tab, Automa won't execute the next block on that new tab.

So to fix this, you need to use the **Link block**. It will grab the URL from the anchor element and open it on the same tab.

**Comment by whwh656** [comment]
Thanks !
