### ISSUE TITLE
trigger event about keydown

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#288]
I want to   press key 'D'  repeatedly  6 times

![image](https://user-images.githubusercontent.com/20383505/151140737-925a6c52-ed64-4563-964d-55db46dbfec0.png)
question1:
I don't understand the funtion about keydown code  and repeat  where i draw  mark1 and mark2

question2:
I try the block of repeat task,but it doesn't work! 
[Uploading shortcut.txt…]()

**Comment by Kholid060** [comment]
> I don't understand the function about keydown code and repeat where I draw mark1 and mark2

The [`code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) input is for the code of the key that is pressed, for example, `KeyQ` for the `Q` key. You can see the list of the key codes on the [MDN Page](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values). 

And for the [`repeat`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat) checkbox, it's to tell if the given key is being held down such that it is automatically repeating.

> I try the block of repeat task, but it doesn't work!
Can you reupload the workflow file? Because it only redirects when I click it.

**Comment by whwh656** [comment]
[testanjian.txt](https://github.com/Kholid060/automa/files/7959619/testanjian.txt)
> Can you reupload the workflow file? Because it only redirects when I click it.
I want to press key 'D' repeatedly 6 times, to move this cube,thanks

**Comment by Kholid060** [comment]
To press 'D' key using the trigger event, use these options:
- [`code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values): `KeyD`
- [`key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values): `d`

And to do it repeatedly, you can use the [repeat task block](https://docs.automa.site/blocks/repeat-task.html)
[testanjian (1).txt](https://github.com/Kholid060/automa/files/7963490/testanjian.1.txt)
![image](https://user-images.githubusercontent.com/22908993/151657696-c6d97d4e-1f00-4acd-af91-6501d217bd6f.png)

**Comment by whwh656** [comment]
Thanks
