### ISSUE TITLE
css selector doesn't work

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#433]
automa:v1.6.7
1  copy this url:
https://modaiyun.meijian.com/damf/site/cmty/mdy/villa/plan/3FO4K4WLH4HL
2 scorll bottom
3 
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/20383505/161979321-6d62b110-3371-4b97-96ab-088c98c48e40.png">

**Comment by Kholid060** [comment]
It's not working because the element that you trying to select is on a [iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) element.

![image](https://user-images.githubusercontent.com/22908993/162100172-d7481e8d-340a-48cb-9403-5f5f09a99248.png)

To select an element inside it, enable the second element selector.

![D9dtMBaRvq](https://user-images.githubusercontent.com/22908993/162100319-d87f6ebf-fee8-4e57-b9e0-0c9f3108075e.png)
