### ISSUE TITLE
waitconnection blcok

### ISSUE THREAD

**Issue by whwh656** [Kholid060/automa#469]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/20383505/165692259-c30facb1-4a4d-42f4-8625-67e99cc567d4.png">
automa :1.9.2
I'm confused abuout this blcok

**Comment by Kholid060** [comment]
> <img alt="image" width="1040" src="https://user-images.githubusercontent.com/20383505/165692259-c30facb1-4a4d-42f4-8625-67e99cc567d4.png">
> 
> automa :1.9.2 I'm confused about this block

Read the [documentation](https://docs.automa.site/blocks/wait-connections.html) to learn more about this block.

And for the `Only continue a specific flow` option, like what the label said it's for continuing only a specific flow. 
For example, when the `wait connections` block has several blocks that connect to it

![chrome_10PyWZZLtJ](https://user-images.githubusercontent.com/22908993/165762053-94899060-7bef-416c-be80-a7230603fd67.png)

instead of making both the `Line A` and the `Line B` execute the `switch tabs` block, it only allows the `Line A` to continue and terminate the other flow (`Line B`).

**Comment by whwh656** [comment]
Thanks
