### ISSUE TITLE
Attribute value block don't get the checked value from input

### ISSUE THREAD

**Issue by guiedinger** [Kholid060/automa#94]
**Describe the bug**
Attribute value block don't get the checked value from input with radio type.

**To Reproduce**
1. Choose an site with an element input with radio type.
![image](https://user-images.githubusercontent.com/13008549/142038923-92a0f6f1-0d11-48ff-a1f8-68dc4866a119.png)
2. Add an "New tab" block to this url.
3. Add "Attribute value" block with the selector of the radio and checked attribute and save to a Boolean Data column.
![image](https://user-images.githubusercontent.com/13008549/142038963-f79ab351-ec1f-4491-bbbd-2b010de4b33f.png)
![image](https://user-images.githubusercontent.com/13008549/142039086-30daede9-1aea-4bf5-b4f9-de2173fd4b8c.png)
4. Save and run and see that always returns false even when is checked.
![image](https://user-images.githubusercontent.com/13008549/142039203-5369f279-a7eb-4698-9b05-ad4221ea6215.png)

**Expected behavior**
The expected behavior is to get the correct boolean value if the input is checked or not.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium Edge 95.

**Comment by Kholid060** [comment]
It's because the extension uses [`getAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute) which only gets the value of the attribute. And in this case, because the `checked` attribute doesn't have a value like `true` nor `false` so the extension doesn't save it.

But I guess, this will be a great improvement that the extension should save the `true` or `false` value of the `checked` attribute.
